### ISSUE TITLE
Re-evaluate use of "exec" as a verb

### ISSUE THREAD

**Issue by sknorr** [SUSE/doc-slert#30]
via @lproven :

If exec is being used a lot in this doc, it poses a question. "Exec" is not a word. If it's a command, I think we should tag it with `<command>exec</command>`. If it's merely used it as shorthand for "execute" then we should either use the word in full, or a shorter one, for example "run".

@tomschr @JeffreyCheung Do you have opinions on this?

**Comment by tomschr** [comment]
Thanks Stefan.

To quantify the amount of "exec's", I did a quick `egrep "[^-]exec.?\s" xml/*` in my local repo. This is what I got:

```
xml/article_setup.xml:    <!-- cset proc .... exec -->
xml/slert_cpuset_manipulation.xml:   <command>proc</command> and it allows you to exec processes into a
xml/slert_cpuset_manipulation.xml:    To exec a task into a cpuset, the <command>proc</command> subcommand
xml/slert_cpuset_manipulation.xml:    exec a shell into the cpuset named <literal>two</literal> in our set.
xml/slert_cpuset_manipulation.xml:     if the command you want to exec also takes options, separate them with
xml/slert_cpuset_manipulation.xml:    forked in preparation for exec, but the command
xml/slert_cpuset_manipulation.xml:    Although the ability to exec a task into a cpuset is fundamental, you
xml/slert_shielding_model.xml:     shield. For this example, let’s exec a new Bash shell into the shield
xml/slert_shielding_model.xml:     The second command execs the Bash shell into the shield with the
xml/slert_shielding_model.xml:      if the command you want to exec also takes options, separate them with
```

From what I can see, yes, "exec" is mostly slang. A sloppy version of _execute_. That should be changed. Maybe even better to replace it with "run".
However, I don't see anything in the above output that is really a command. I do not think the above "exec"s should be wrapped in `<command>`.

**Comment by sknorr** [comment]
@tomschr Your listing is missing the mentions of "execing", "execs" and "execed". :)

**Comment by tomschr** [comment]
> @tomschr Your listing is missing mentions of "execing", "execs" and "execed". :)

True. But these aren't commands anyway. :wink:

**Comment by sknorr** [comment]
People do use stuff like "sshing" too.
And mentions of execing/execs/execed should be fixed as well.

**Comment by tomschr** [comment]
True. I've amended the regex:

```
$ egrep "([^-]exec.?\s|execing|execed)" xml/*
xml/article_setup.xml:<!-- cset proc .... exec -->
xml/slert_cpuset_manipulation.xml:   <command>proc</command> and it allows you to exec processes into a
xml/slert_cpuset_manipulation.xml:    To exec a task into a cpuset, the <command>proc</command> subcommand
xml/slert_cpuset_manipulation.xml:    exec a shell into the cpuset named <literal>two</literal> in our set.
xml/slert_cpuset_manipulation.xml:    the shell which we execed and the <command>python cset</command> command
xml/slert_cpuset_manipulation.xml:     options from the command to be execed options with a double dash
xml/slert_cpuset_manipulation.xml:     if the command you want to exec also takes options, separate them with
xml/slert_cpuset_manipulation.xml:     execed, the result may be puzzling. For example:
xml/slert_cpuset_manipulation.xml:    forked in preparation for exec, but the command
xml/slert_cpuset_manipulation.xml:    Although the ability to exec a task into a cpuset is fundamental, you
xml/slert_shielding_model.xml:     shield. For this example, let’s exec a new Bash shell into the shield
xml/slert_shielding_model.xml:     The second command execs the Bash shell into the shield with the
xml/slert_shielding_model.xml:      options from the command to be execed options with a double dash
xml/slert_shielding_model.xml:      if the command you want to exec also takes options, separate them with
xml/slert_shielding_model.xml:     While execing a process into the shield is undoubtedly useful, most of
xml/slert_usingshortcuts.xml:   For the common use case of actually shielding either a PIDSPEC or execing
```

The amount of your new suggestions:

```
$ egrep "(execing|execs|execed)" xml/* | wc --lines
7
```

**Comment by lproven** [comment]
I will look in more detail but while copy-editing the whole book, I found:

>  To start a new process in the shielded CPU set, use the <option>--exec</option> option:

I think this may be what is meant, and if so, while no it is _not_ a command, this is a separate usage from "run" or indeed "execute".

**Comment by sknorr** [comment]
>I think this may be what is meant, and if so, while no it is not a command, this is a separate usage from "run" or indeed "execute".

Well, I just did it anyway. (I don't think this reasoning holds too much water tbh.)
